### ISSUE TITLE
The remote server returned an error: (415)

### ISSUE THREAD

**Issue by fravokado** [ntisservices/ntis-dotnet-web-services-Release2.5#1]
We have encountered a problem in initial testing. We have done everything according to your instructions. We manage to start the service on our local server, but when we try to invoke method for pulling data from your system, we get an error saying:

"The remote server returned an error: (415) Cannot process the message because the content type 'application/soap+xml; charset=utf-8; action="http://datex2.eu/wsdl/supplierPush/2_0/putDatex2Data"' was not the expected type 'text/xml;charset=UTF-8'".

After some research on the web, we discovered that the other developers with the same error found solution in mismatching versions of SOAP messages, or binding configuration in web.config file.

Was there any change in configuration on your side that we are not aware of?

Thank you in advance for your help!

**Comment by ntisservices** [comment]
We did not encounter this problem during our system testing, and we know that a number of Subscribers are using this software successfully.  Did you perform the SOAP UI tests, as outlined in the README?  To answer your question, the version in this repository should not require any modification; there were no other configuration changes.  It should be borne in mind that this is example software, to be used as a 'starting point' for your project; the software has been proven only on the platforms and software versions specified in the README.

Apologies that I cannot assist further.
